// src/env.d.ts
declare namespace NodeJS {
  interface ProcessEnv {
    GOOGLE_MAPS_API_KEY: string;
    APPWRITE_ENDPOINT: string;
    APPWRITE_PROJECT_ID: string;
    APPWRITE_PLATFORM_ID: string;
    APPWRITE_DATABASE_ID: string;
    APPWRITE_USER_COLLECTION_ID: string;
    APPWRITE_SHELTER_COLLECTION_ID: string;
    APPWRITE_SHELTER_IMAGES_COLLECTION_ID: string;
    APPWRITE_REGION_COLLECTION_ID: string;
    APPWRITE_DISTRICT_COLLECTION_ID: string;
    APPWRITE_SIZE_COLLECTION_ID: string;
    APPWRITE_TYPE_COLLECTION_ID: string;
    APPWRITE_BREED_COLLECTION_ID: string;
    APPWRITE_PET_COLLECTION_ID: string;
    APPWRITE_PET_IMAGE_COLLECTION_ID: string;
    APPWRITE_CURRENCIES_COLLECTION_ID: string;
    APPWRITE_USER_PET_ACTIONS_COLLECTION_ID: string;
    APPWRITE_SHELTER_STORAGE_ID: string;
    APPWRITE_PET_STORAGE_ID: string;
  }
}
